services:
  pmt:
    build:
      context: .
      dockerfile: pmt/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  ihm:
    build:
      context: ./ihm
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
